# Generated by Django 4.2 on 2026-08-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elevation_gain', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
